version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: "kphp"
      POSTGRES_USER: "vadim"
      POSTGRES_PASSWORD: "vadim"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - published: 5432
        target: 5432
        host_ip: "127.0.0.1"
    networks:
      - kphp_network

networks:
  kphp_network:
    external: true