FROM ubuntu:focal
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake make clang g++ g++-10 gdb gdbserver \
    openssh-server rsync

# Настраиваем ssh сервер
RUN echo 'root:root' | chpasswd && \
    mkdir /var/run/sshd && \
    sed -i 's\#PermitRootLogin prohibit-password\PermitRootLogin yes\ ' /etc/ssh/sshd_config

EXPOSE 22 7777

CMD ["/usr/sbin/sshd", "-D"]
